name: 1.0
pool:
  vmImage: ubuntu-latest
trigger:
- main
variables:
- group: AZURE-CREDENTIALS

stages:
- stage: validate_plan
  displayName: Validate & Plan
  jobs:
  - job: validate_plan
    displayName: Validate & Plan
    steps:
    - script: |
        terraform init
        terraform validate
        terraform plan -out plan.out
      displayName: Terraform Validate & Plan
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        TF_VAR_aws_key_pub: $(TF_VAR_aws_key_pub)
        TF_VAR_azure_key_pub: $(TF_VAR_azure_key_pub)
    - publish: $(Build.SourcesDirectory)/plan.out
      artifact: plan
      displayName: Publish Plan

- stage: apply
  displayName: Apply
  jobs:
  - job: apply
    displayName: Terraform Apply
    steps:
    - download: current
      artifact: plan
      displayName: Download Plan
    - script: |
        terraform init
        terraform apply $(Pipeline.Workspace)/plan/plan.out
      displayName: Terraform Apply
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)

- stage: destroy
  displayName: Destroy
  jobs:
  - job: destroy
    displayName: Terraform Destroy
    steps:
    - script: |
        terraform init
        terraform destroy -auto-approve
      displayName: Terraform Destroy
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)